### ISSUE TITLE
Now to use the NuGet package 

### ISSUE THREAD

**Issue by scleaver** [Lombiq/.NET-Analyzers#40]
The instructions cover adding this to your solution using a submodule method but do not cover how to utilise this from the NuGet package.

Could we have some clarification on this.

**Comment by Piedone** [comment]
All NuGet publishing is WIP. Docs were added under this yet open PR: https://github.com/Lombiq/.NET-Analyzers/pull/39

**Comment by Piedone** [comment]
In the meantime, this is now also released: https://github.com/Lombiq/.NET-Analyzers/blob/dev/Docs/AddingAnalyzers.md#how-to-add-the-analyzers-to-sdk-style-projects-from-nuget
