### ISSUE TITLE
Static code analysis randomly crashes with "MSB6006: "csc.dll" exited with code 139." (OSOE-725)

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/.NET-Analyzers#95]
This has happened a couple of times, but very rarely. Restarting the workflow fixes the problem.
An example is [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/6839154364/attempts/1?pr=602), however it's not related to that issue (compilation failed in Lombiq.SetupExtensions.csproj which doesn't use nodejs) and I've seen it appear in other branches too, it's just the latest one at the time of writing. I've checked [the attached binlog](https://github.com/Lombiq/.NET-Analyzers/files/13327513/build-binary-log-.-Linux-X64-buildjet.com_903bf564-b694-4dcc-bffa-00bbe0e99a54.binlog.zip) but didn't see anything significant in it.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-725)

**Comment by Piedone** [comment]
This is a known issue of the compiler at least on GHA with Ubuntu: https://github.com/actions/runner/issues/2615 I don't think we can do anything with it.

**Comment by Piedone** [comment]
So, the only thing we can do here is wait.
